#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md", "vendor"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Shantea Controls - DIY MIDI solutions
# Website language
lang: en-US
# Header Title
header-title: Plug and play. <strong>REALLY</strong>.
# Header Tagline
headter-tagline: OpenDeck DIY MIDI platform

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Buy now
  url: https://www.tindie.com/products/paradajz/opendeck-diy-midi-platform/

# Secondary Buttons
header-secondary-button:
  title: Configurator
  url: https://paradajz.github.io/OpenDeck

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
banner-link: https://www.tindie.com/products/paradajz/opendeck-diy-midi-platform/

####################################
######  Global Social Links   ######
####################################
youtube: 'https://youtube.com/shanteacontrols'
facebook: 'https://www.facebook.com/shanteacontrolsmidi'

#########################
######   Widgets   ######
#########################

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Build MIDI controllers with ease
about-description: Instead of spending time on circuit design, programming, and solving lots of unnecessary problems, simply connect components of your MIDI controller into OpenDeck board and you’re done.

#####################################
#############   Configurator   #############
#####################################
configurator-title: Extreme configurability
configurator-description: Additional board configuration can be done online  – no installation of extra software is necessary!


#####################################
#############  Features  ############
#####################################
features-title: Packed with features
features-description: OpenDeck is the most featureful and configurable MIDI platform on the planet.

#
# Features
#
features:

- title: Simple
  description: Simplicity is a feature.
  icon: pe-7s-smile

- title: Universally supported
  description: Windows, macOS, Linux, Android, iOS or standalone. Any DAW or DJ software with MIDI support.
  icon: pe-7s-smile

- title: Online configurator
  description: Configure every aspect of your controller with online configurator. No installation required.
  icon: pe-7s-smile

- title: Open source
  description: 100% open-source and open-hardware
  icon: pe-7s-smile

- title: Custom board support
  description: Easily add support for yours!
  icon: pe-7s-smile

- title: Battle proven
  description: Stable and reliable. Running inside custom controllers for world-class musicians.
  icon: pe-7s-smile

- title: Inputs
  description: Buttons, potentiometers, FSRs, encoders
  icon: pe-7s-smile

- title: Outputs
  description: Single color and RGB LEDs
  icon: pe-7s-smile

- title: Touchscreen support
  description: All Nextion and Stone HMI models
  icon: pe-7s-smile

- title: DIN MIDI
  description: Connect synths and other gear
  icon: pe-7s-smile

- title: USB MIDI
  description: No drivers required
  icon: pe-7s-smile

- title: MIDI configuration
  description: Configurable MIDI channels and messages
  icon: pe-7s-smile

- title: Presets
  description: Up to 10 individual mappings
  icon: pe-7s-smile

- title: 14-bit support
  description: Pitch bend, high-resolution CC and NRPN support
  icon: pe-7s-smile

- title: Firmware updates in browser
  description: Update your board with new features
  icon: pe-7s-smile

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Built with OpenDeck
portfolio-description: Check the examples below and see what is possible with OpenDeck.

#
# Portfolio Grid
#
portfolio-categories: [Shantea Controls, DubFocus, Bergamot, Rooibos, User made]
portfolio:

- title: Cardamom
  categories: [Shantea Controls]
  image: cardamom.jpg
  url:

- title: Bergamot
  categories: [Shantea Controls, Bergamot]
  image: bergamot.jpg
  url: 'https://shanteacontrols.com'

- title: Bergamot
  categories: [Shantea Controls, Bergamot]
  image: bergamot_2.jpg
  url:

- title: Bergamot
  categories: [Shantea Controls, Bergamot]
  image: bergamot_3.jpg
  url:

- title: Bergamot
  categories: [Shantea Controls, Bergamot]
  image: bergamot_4.jpg
  url:

- title: Bergamot
  categories: [Shantea Controls, Bergamot]
  image: bergamot_5.jpg
  url:

- title: Rooibos
  categories: [Shantea Controls, Rooibos]
  image: rooibos_2.jpg
  url:

- title: Rooibos
  categories: [Shantea Controls, Rooibos]
  image: rooibos_3.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12_2.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12_3.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12_4.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12_5.jpg
  url:

- title: DubFocus 12
  categories: [Shantea Controls, DubFocus]
  image: df12_6.jpg
  url:

- title: DubFocus16
  categories: [Shantea Controls, DubFocus]
  image: df16.jpg
  url:

- title: DubFocus16
  categories: [Shantea Controls, DubFocus]
  image: df16_2.jpg
  url:

- title: DubFocus16
  categories: [Shantea Controls, DubFocus]
  image: df16_3.jpg
  url:

- title: DubFocus16
  categories: [Shantea Controls, DubFocus]
  image: df16_4.jpg
  url:

- title: Made for Jamiel Allen
  categories: [Shantea Controls]
  image: jamiel.jpg
  url:

- title: Made for Jamiel Allen
  categories: [Shantea Controls]
  image: jamiel_2.jpg
  url:

- title: Built by Michael LaChance
  categories: [User made]
  image: lachance.jpg
  url:

- title: Built by Rich Parker
  categories: [User made]
  image: parker.jpg
  url:

- title: Built by Chad Kettering
  categories: [User made]
  image: chad.jpg
  url:

- title: Built by Morten Berthelsen
  categories: [User made]
  image: morten.jpg
  url:


#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: OpenDeck is the most configurable MIDI platform on the planet.

#
# Core Features Left
#
core-features-left:

# Feature


#
# Core Features Right
#
core-features-right:


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Users just love OpenDeck. But don't take my word for it.

#
# Testimonials
#
testimonials:

- name: Liam Lacey
  url: https://ask.audio/articles/review-shantea-controls-opendeck-custom-midi-controller-platform
  url-text: ask.audio
  cite: "(...) the most affordable and flexible platform for building your own custom MIDI controllers."

- name: Steve
  url: https://www.tindie.com/products/paradajz/opendeck-diy-midi-platform/
  url-text: Tindie review
  cite: "The new interface is a triumph of usability and make configuring the controllers very easy indeed. In my opinion, this is the best MIDI controller available"

- name: Manuel
  url: https://www.tindie.com/products/paradajz/opendeck-diy-midi-platform/
  url-text: Tindie review
  cite: "It's the pointy, finished and perfect board for all your DIY MIDI"

- name: Ben Garland
  url: https://www.tindie.com/products/paradajz/opendeck-diy-midi-platform/
  url-text: Tindie review
  cite: "OpenDeck makes me excited for MIDI controllers like never before. It takes just a few MINUTES to get up and running with OpenDeck! It's literally plug and PLAY!"

- name: Scott Koopmann
  url: 
  url-text: Review sent via contact form
  cite: "OpenDeck is the future of DIY MIDI controller builds. Hands down"

- name: David Dyball
  url: 
  url-text: Review sent via contact form
  cite: "I’m just blown away with how amazing this is. The web interface is super simple and really smooth to use."

- name: Barry Limestone
  url: 
  url-text: Review sent via contact form
  cite: "Literally the greatest product related to MIDI controls I have ever seen"

- name: Andrey
  url: 
  url-text: Review sent via contact form
  cite: "wow it works right out of the box, impressive"


#####################################
############# Our Blog ##############
#####################################
blog-title: Latest blog posts
blog-description:


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:

# Team Member
- name: Jack Skilton
  tagline: Graphic Designer
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'


pricing-title: Prices for custom MIDI controllers
pricing-description: Want a custom controller, but don't want to DIY? Check the offers below.

price-offer-1-title: Rooibos
price-offer-1-price: $650
price-offer-1-info: Make any layout you want with 10" touchscreen.

price-offer-2-title: DubFocus 16
price-offer-2-price: $1200
price-offer-2-info: The ultimate dubbing controller. Dub in the box like never before. 16 channels, 4 sends, 2 buttons with LEDs and 1 fader per channel strip.

price-offer-3-title: Custom design
price-offer-3-price: Send a message for the offer
price-offer-3-info: Want a fully custom controller or custom board design? OpenDeck can accomodate virtually any MIDI controller you have in mind.


#####################################
############   Contact   ############
#####################################
contact-title: Contact
contact-description: Want to know more about OpenDeck? Interested in custom MIDI controller? Send a message!


#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: Shantea Controls
footer-copyright-url: http://shanteacontrols.com/
footer-copyright-year: 2021